// <auto-generated />
using System;
using ExpenseTrackerCoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExpenseTrackerCoreMVC.Migrations
{
    [DbContext(typeof(ExpenseTrackerCoreMVCDbContext))]
    [Migration("20250827100529_InitialCreateWithSeed")]
    partial class InitialCreateWithSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExpenseTrackerCoreMVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Education"
                        },
                        new
                        {
                            Id = 6,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 7,
                            DateAdded = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Insurance"
                        });
                });

            modelBuilder.Entity("ExpenseTrackerCoreMVC.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1500.00m,
                            CategoryId = 1,
                            DateAdded = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 300.00m,
                            CategoryId = 2,
                            DateAdded = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 50.00m,
                            CategoryId = 3,
                            DateAdded = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gasoline"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 20.00m,
                            CategoryId = 4,
                            DateAdded = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Movie Night"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 100.00m,
                            CategoryId = 5,
                            DateAdded = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Books"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 200.00m,
                            CategoryId = 6,
                            DateAdded = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doctor's Visit"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 100.00m,
                            CategoryId = 7,
                            DateAdded = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Insurance Premium"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 75.00m,
                            CategoryId = 1,
                            DateAdded = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Phone Bill"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 60.00m,
                            CategoryId = 1,
                            DateAdded = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Water Bill"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 120.00m,
                            CategoryId = 1,
                            DateAdded = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 25.00m,
                            CategoryId = 2,
                            DateAdded = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Snacks"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 400.00m,
                            CategoryId = 2,
                            DateAdded = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Supermarket"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 15.00m,
                            CategoryId = 3,
                            DateAdded = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Taxi"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 10.00m,
                            CategoryId = 3,
                            DateAdded = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bus Fare"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 75.00m,
                            CategoryId = 4,
                            DateAdded = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Concert Ticket"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 200.00m,
                            CategoryId = 5,
                            DateAdded = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Online Course"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 500.00m,
                            CategoryId = 5,
                            DateAdded = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tuition Fee"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 350.00m,
                            CategoryId = 6,
                            DateAdded = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hospital Bill"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 80.00m,
                            CategoryId = 6,
                            DateAdded = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Medicine"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 150.00m,
                            CategoryId = 6,
                            DateAdded = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dental Checkup"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 250.00m,
                            CategoryId = 7,
                            DateAdded = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Car Insurance"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 180.00m,
                            CategoryId = 7,
                            DateAdded = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Health Insurance"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 220.00m,
                            CategoryId = 7,
                            DateAdded = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Home Insurance"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 15.00m,
                            CategoryId = 4,
                            DateAdded = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Streaming Service"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 30.00m,
                            CategoryId = 4,
                            DateAdded = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Cinema"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 40.00m,
                            CategoryId = 5,
                            DateAdded = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Stationery"
                        },
                        new
                        {
                            Id = 27,
                            Amount = 120.00m,
                            CategoryId = 5,
                            DateAdded = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 28,
                            Amount = 300.00m,
                            CategoryId = 1,
                            DateAdded = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 29,
                            Amount = 200.00m,
                            CategoryId = 2,
                            DateAdded = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Grocery Refill"
                        },
                        new
                        {
                            Id = 30,
                            Amount = 50.00m,
                            CategoryId = 6,
                            DateAdded = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gym Membership"
                        });
                });

            modelBuilder.Entity("ExpenseTrackerCoreMVC.Models.Expense", b =>
                {
                    b.HasOne("ExpenseTrackerCoreMVC.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpenseTrackerCoreMVC.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
